spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  datasource:
    url: 'jdbc:postgresql://localhost:5432/sd_project'
    username: 'postgres'
    password: '0000'

  flyway:
    clean-on-validation-error: true
    schemas: project

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        default_schema: project
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver

  flyway:
    clean-on-validation-error: true
    schemas: project

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        default_schema: project
    hibernate:
      ddl-auto: create

---


spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver

  flyway:
    clean-on-validation-error: true
    schemas: project

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        default_schema: project
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        security: DEBUG
